/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okesalon.view.transaksi;
import com.okesalon.dao.TransaksiPenjualanProdukDAO;
import com.okesalon.dao.ProdukDAO;
import com.okesalon.model.TransaksiPenjualanProduk;
import com.okesalon.model.Produk;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;
/**
 *
 * @author T480
 */
public class FormTransaksiPenjualanProduk extends javax.swing.JPanel {
    // ==================== INSTANCE VARIABLES ====================
    private TransaksiPenjualanProdukDAO transaksiPenjualanProdukDAO;
    private ProdukDAO produkDAO;
    private DefaultTableModel tableModel;
    private TransaksiPenjualanProduk selectedTransaksi = null;
    /**
     * Creates new form FormTransaksiProdukJual
     */
    public FormTransaksiPenjualanProduk() {
        initComponents();
        // Initialize DAOs
        transaksiPenjualanProdukDAO = new TransaksiPenjualanProdukDAO();
        produkDAO = new ProdukDAO();
        
        // Initialize Table
        initTable();
        
        // Setup ComboBoxes
        setupComboBoxes();
        
        // Load Data
        loadProdukToComboBox();
        loadPelangganToComboBox();
        loadDataToTable();
        
        // Setup Events
        setupComboBoxKeyReleased();
        setupAutoCalculation();
        
        // Set Default Date
        tanggal.setDate(new Date());
        
        System.out.println("✅ FormTransaksiPenjualanProduk initialized!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnViewPelanggan = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabel_penjualan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        nama_produk = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jumlah_beli = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        harga_satuan = new javax.swing.JTextField();
        id_produk = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        metode_pembayaran = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextArea();
        nama_pelanggan = new javax.swing.JComboBox<>();
        id_pelanggan = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        stok_sebelum = new javax.swing.JTextField();
        stok_sesudah = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        total_harga = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jumlah_jual = new javax.swing.JTextField();
        btnViewDetailPenjualan = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 153, 255));
        jPanel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnTambah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCari.setText("CARI");
        btnCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarijButton4ActionPerformed(evt);
            }
        });

        txtCari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarijTextField14ActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnViewPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnViewPelanggan.setText("View Pelanggan");
        btnViewPelanggan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPelangganjButton5ActionPerformed(evt);
            }
        });

        tabel_penjualan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabel_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penjualanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabel_penjualan);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        jLabel1.setText("Transaksi Penjualan Produk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 220, 255));

        jPanel3.setBackground(new java.awt.Color(255, 102, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INFO PRODUK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("Tanggal Transaksi");

        tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Nama Produk");

        nama_produk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_produk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("Jumlah Beli");

        jumlah_beli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jumlah_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_belijTextField7ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("Harga Satuan");

        harga_satuan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        harga_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_satuanjTextField8ActionPerformed(evt);
            }
        });

        id_produk.setEditable(false);
        id_produk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_produkjTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel28))
                        .addGap(84, 84, 84)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah_beli)
                    .addComponent(harga_satuan)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(id_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 220, 255));

        jPanel8.setBackground(new java.awt.Color(255, 102, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INFO PELANGGAN & PEMBAYARAN");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setText("Nama Pelanggan");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setText("Nomor Telepon");

        telepon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponjTextField9ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setText("Metode Pembayaran");

        metode_pembayaran.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        metode_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Qris", "Transfer Bank" }));
        metode_pembayaran.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        metode_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metode_pembayaranjComboBox1ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setText("Keterangan");

        keterangan.setColumns(20);
        keterangan.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        keterangan.setRows(5);
        jScrollPane6.setViewportView(keterangan);

        nama_pelanggan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_pelanggan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        id_pelanggan.setEditable(false);
        id_pelanggan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pelangganjTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel37))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(metode_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(telepon)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(nama_pelanggan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(id_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(metode_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 220, 255));

        jPanel12.setBackground(new java.awt.Color(255, 102, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DETAIL & SUMMARY");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setText("Stok Sebelum");

        stok_sebelum.setEditable(false);
        stok_sebelum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        stok_sebelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_sebelumjTextField11ActionPerformed(evt);
            }
        });

        stok_sesudah.setEditable(false);
        stok_sesudah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        stok_sesudah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_sesudahjTextField12ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("Stok Sesudah");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setText("Total Harga");

        total_harga.setEditable(false);
        total_harga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_hargajTextField9ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setText("Jumlah Jual");

        jumlah_jual.setEditable(false);
        jumlah_jual.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jumlah_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_jualjTextField12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(99, 99, 99)
                        .addComponent(total_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel40))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stok_sebelum, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jumlah_jual)
                            .addComponent(stok_sesudah))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_sebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah_jual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_sesudah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        btnViewDetailPenjualan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnViewDetailPenjualan.setText("View Detail Penjualan");
        btnViewDetailPenjualan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDetailPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailPenjualanjButton5ActionPerformed(evt);
            }
        });

        btnHAPUS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHAPUS.setText("HAPUS");
        btnHAPUS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewDetailPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(642, 642, 642)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDetailPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, "card2");

        add(jPanel4, "card3");
    }// </editor-fold>//GEN-END:initComponents

   // ==================== INIT TABLE (NO ACTIONS COLUMN) ====================
    
    private void initTable() {
        String[] columns = {
            "Kode Transaksi", 
            "Tanggal", 
            "Nama Produk", 
            "Pelanggan",
            "Jumlah", 
            "Total Harga",
            "Pembayaran"
        };
        
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tabel_penjualan.setModel(tableModel);
        tabel_penjualan.setRowHeight(30);
        tabel_penjualan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // Column widths
        tabel_penjualan.getColumnModel().getColumn(0).setPreferredWidth(150); // Kode
        tabel_penjualan.getColumnModel().getColumn(1).setPreferredWidth(100); // Tanggal
        tabel_penjualan.getColumnModel().getColumn(2).setPreferredWidth(250); // Nama Produk
        tabel_penjualan.getColumnModel().getColumn(3).setPreferredWidth(200); // Pelanggan
        tabel_penjualan.getColumnModel().getColumn(4).setPreferredWidth(100); // Jumlah
        tabel_penjualan.getColumnModel().getColumn(5).setPreferredWidth(150); // Total
        tabel_penjualan.getColumnModel().getColumn(6).setPreferredWidth(120); // Pembayaran
        
        // Renderers
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tabel_penjualan.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tabel_penjualan.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        
        System.out.println("✅ Table initialized (7 columns)");
    }
    
    // ==================== SETUP COMBOBOXES ====================
    
    private void setupComboBoxes() {
        metode_pembayaran.removeAllItems();
        metode_pembayaran.addItem("Cash");
        metode_pembayaran.addItem("Qris");
        metode_pembayaran.addItem("Transfer Bank");
        
        System.out.println("✅ ComboBoxes setup!");
    }
    
    // ==================== LOAD PRODUK TO COMBOBOX ====================
    
    private void loadProdukToComboBox() {
        try {
        System.out.println("🔄 Loading produk to ComboBox...");
        
        // Clear existing items
        nama_produk.removeAllItems();
        nama_produk.addItem("-- Pilih Produk --");
        
        // Get data from DAO
        List<String> namaProdukList = transaksiPenjualanProdukDAO.getNamaProdukList();
        
        System.out.println("📦 Retrieved " + namaProdukList.size() + " produk from database");
        
        // Check if list is empty
        if (namaProdukList.isEmpty()) {
            System.out.println("⚠️ WARNING: No produk found in database!");
            JOptionPane.showMessageDialog(this,
                "⚠️ Tidak ada produk di database!\n\nSilakan tambah produk terlebih dahulu.",
                "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Add items to ComboBox
        for (String nama : namaProdukList) {
            nama_produk.addItem(nama);
            System.out.println("  ✅ Added: " + nama);
        }
        
        System.out.println("✅ Loaded " + namaProdukList.size() + " produk to ComboBox");
        
    } catch (Exception e) {
        System.err.println("❌ ERROR in loadProdukToComboBox(): " + e.getMessage());
        e.printStackTrace();
        
        JOptionPane.showMessageDialog(this,
            "❌ Error loading produk:\n\n" + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    
    // ==================== LOAD PELANGGAN TO COMBOBOX ====================
    
    private void loadPelangganToComboBox() {
        nama_pelanggan.removeAllItems();
        nama_pelanggan.addItem("-- Pilih Pelanggan --");
        
        List<String> pelangganList = transaksiPenjualanProdukDAO.getAllNamaPelanggan();
        
        for (String pelanggan : pelangganList) {
            nama_pelanggan.addItem(pelanggan);
        }
        
        System.out.println("✅ Loaded " + pelangganList.size() + " pelanggan");
    }
    
    // ==================== SETUP COMBOBOX KEY RELEASED ====================
    
    private void setupComboBoxKeyReleased() {
        // ✅ SET COMBOBOX JADI EDITABLE DULU!
        nama_produk.setEditable(true);
        nama_pelanggan.setEditable(true);

        // Get editor component
        JTextField produkEditor = (JTextField) nama_produk.getEditor().getEditorComponent();
        JTextField pelangganEditor = (JTextField) nama_pelanggan.getEditor().getEditorComponent();

        // ✅ KeyReleased untuk nama_produk
        produkEditor.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String text = produkEditor.getText().trim();

                if (!text.isEmpty() && !text.startsWith("--")) {
                    filterProdukComboBox(text);
                } else if (text.isEmpty()) {
                    loadProdukToComboBox();
                }
            }
        });

        // ✅ KeyReleased untuk nama_pelanggan
        pelangganEditor.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String text = pelangganEditor.getText().trim();

                if (!text.isEmpty() && !text.startsWith("--")) {
                    filterPelangganComboBox(text);
                } else if (text.isEmpty()) {
                    loadPelangganToComboBox();
                }
            }
        });

        // ✅ ActionListener untuk auto-fill saat dipilih dari dropdown
        nama_produk.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object selected = nama_produk.getSelectedItem();

                if (selected != null) {
                    String selectedText = selected.toString();
                    if (!selectedText.startsWith("--")) {
                        loadProdukData(selectedText);
                    }
                }
            }
        });

        nama_pelanggan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object selected = nama_pelanggan.getSelectedItem();

                if (selected != null) {
                    String selectedText = selected.toString();
                    if (!selectedText.startsWith("--")) {
                        loadPelangganData(selectedText);
                    }
                }
            }
        });

        System.out.println("✅ ComboBox KeyReleased setup!");
    }
    
    // ==================== FILTER PRODUK COMBOBOX ====================
    
    private void filterProdukComboBox(String keyword) {
        List<String> allProduk = transaksiPenjualanProdukDAO.getNamaProdukList();
        List<String> filtered = new ArrayList<>();

        for (String nama : allProduk) {
            if (nama.toLowerCase().contains(keyword.toLowerCase())) {
                filtered.add(nama);
            }
        }

        // Disable action listener temporarily
        ActionListener[] listeners = nama_produk.getActionListeners();
        for (ActionListener listener : listeners) {
            nama_produk.removeActionListener(listener);
        }

        // Update items
        nama_produk.removeAllItems();
        nama_produk.addItem("-- Pilih Produk --");
        for (String nama : filtered) {
            nama_produk.addItem(nama);
        }

        // Re-add listeners
        for (ActionListener listener : listeners) {
            nama_produk.addActionListener(listener);
        }

        // Show dropdown if results found
        if (!filtered.isEmpty()) {
            nama_produk.setPopupVisible(true);
        }

        System.out.println("✅ Filtered produk: " + filtered.size() + " results");
    }
    
    // ==================== FILTER PELANGGAN COMBOBOX ====================
    
    private void filterPelangganComboBox(String keyword) {
        List<String> allPelanggan = transaksiPenjualanProdukDAO.getAllNamaPelanggan();
        List<String> filtered = new ArrayList<>();

        for (String pelanggan : allPelanggan) {
            if (pelanggan.toLowerCase().contains(keyword.toLowerCase())) {
                filtered.add(pelanggan);
            }
        }

        // Disable action listener temporarily
        ActionListener[] listeners = nama_pelanggan.getActionListeners();
        for (ActionListener listener : listeners) {
            nama_pelanggan.removeActionListener(listener);
        }

        // Update items
        nama_pelanggan.removeAllItems();
        nama_pelanggan.addItem("-- Pilih Pelanggan --");
        for (String pelanggan : filtered) {
            nama_pelanggan.addItem(pelanggan);
        }

        // Re-add listeners
        for (ActionListener listener : listeners) {
            nama_pelanggan.addActionListener(listener);
        }

        // Show dropdown if results found
        if (!filtered.isEmpty()) {
            nama_pelanggan.setPopupVisible(true);
        }

        System.out.println("✅ Filtered pelanggan: " + filtered.size() + " results");
    }
    
    // ==================== LOAD PRODUK DATA ====================
    
    private void loadProdukData(String namaProduk) {
        try {
            String kodeProduk = transaksiPenjualanProdukDAO.getKodeProdukByNama(namaProduk);
            
            if (kodeProduk != null) {
                Map<String, Object> data = transaksiPenjualanProdukDAO.getProdukData(kodeProduk);
                
                if (!data.isEmpty()) {
                    id_produk.setText(kodeProduk);
                    harga_satuan.setText(String.valueOf(data.get("harga_jual")));
                    
                    int stokSebelum = (int) data.get("stok_saat_ini");
                    stok_sebelum.setText(String.valueOf(stokSebelum));
                    
                    calculateStokSesudah();
                    
                    System.out.println("✅ Loaded: " + namaProduk);
                }
            }
        } catch (Exception e) {
            System.err.println("❌ Error: " + e.getMessage());
        }
    }
    
    // ==================== LOAD PELANGGAN DATA ====================
    
    private void loadPelangganData(String namaPelanggan) {
        try {
            Map<String, Object> data = transaksiPenjualanProdukDAO.getPelangganData(namaPelanggan);
            
            if (!data.isEmpty()) {
                telepon.setText((String) data.get("telepon_pelanggan"));
                System.out.println("✅ Loaded pelanggan: " + namaPelanggan);
            }
        } catch (Exception e) {
            System.err.println("❌ Error: " + e.getMessage());
        }
    }
    
    // ==================== SETUP AUTO CALCULATION ====================
    
    private void setupAutoCalculation() {
        jumlah_beli.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                calculateTotal();
                calculateStokSesudah();
            }
        });
        
        harga_satuan.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                calculateTotal();
            }
        });
        
        System.out.println("✅ Auto calculation setup!");
    }
    
    // ==================== CALCULATE STOK SESUDAH ====================
    
    private void calculateStokSesudah() {
        try {
            String stokSebelumStr = stok_sebelum.getText().trim();
            String jumlahJualStr = jumlah_beli.getText().trim();
            
            if (!stokSebelumStr.isEmpty() && !jumlahJualStr.isEmpty()) {
                int stokSebelum = Integer.parseInt(stokSebelumStr);
                int jumlahJual = Integer.parseInt(jumlahJualStr);
                int stokSesudah = stokSebelum - jumlahJual;
                
                if (stokSesudah < 0) {
                    JOptionPane.showMessageDialog(this,
                        "⚠️ Stok tidak mencukupi! Stok tersedia: " + stokSebelum,
                        "Warning", JOptionPane.WARNING_MESSAGE);
                    jumlah_beli.setText("");
                    stok_sesudah.setText("");
                    jumlah_jual.setText("");
                    return;
                }
                
                stok_sesudah.setText(String.valueOf(stokSesudah));
                jumlah_jual.setText(String.valueOf(jumlahJual));
            }
        } catch (NumberFormatException e) {
            // Ignore
        }
    }
    
    // ==================== CALCULATE TOTAL ====================
    
    private void calculateTotal() {
        try {
            String jumlahStr = jumlah_beli.getText().trim();
            String hargaStr = harga_satuan.getText().trim();
            
            if (!jumlahStr.isEmpty() && !hargaStr.isEmpty()) {
                int jumlah = Integer.parseInt(jumlahStr);
                double harga = Double.parseDouble(hargaStr);
                double total = jumlah * harga;
                
                DecimalFormat df = new DecimalFormat("#,###");
                total_harga.setText("Rp " + df.format(total));
            }
        } catch (NumberFormatException e) {
            // Ignore
        }
    }
    
    // ==================== LOAD DATA TO TABLE ====================
    
    private void loadDataToTable() {
        tableModel.setRowCount(0);
        
        List<TransaksiPenjualanProduk> transaksiList = transaksiPenjualanProdukDAO.getAllTransaksi();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        DecimalFormat currencyFormat = new DecimalFormat("#,###");
        
        for (TransaksiPenjualanProduk transaksi : transaksiList) {
            Object[] row = {
                transaksi.getKodeTransaksi(),
                dateFormat.format(transaksi.getTanggalTransaksi()),
                transaksi.getNamaProduk(),
                transaksi.getNamaPelanggan(),
                transaksi.getJumlahJual() + " pcs",
                "Rp " + currencyFormat.format(transaksi.getTotalHarga()),
                transaksi.getMetodePembayaran()
            };
            tableModel.addRow(row);
        }
        
        System.out.println("✅ Loaded " + transaksiList.size() + " records");
    }
    
    // ==================== SEARCH ====================
    
    private void searchTransaksi() {
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            loadDataToTable();
            return;
        }
        
        tableModel.setRowCount(0);
        
        List<TransaksiPenjualanProduk> transaksiList = transaksiPenjualanProdukDAO.searchTransaksi(keyword);
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        DecimalFormat currencyFormat = new DecimalFormat("#,###");
        
        for (TransaksiPenjualanProduk transaksi : transaksiList) {
            Object[] row = {
                transaksi.getKodeTransaksi(),
                dateFormat.format(transaksi.getTanggalTransaksi()),
                transaksi.getNamaProduk(),
                transaksi.getNamaPelanggan(),
                transaksi.getJumlahJual() + " pcs",
                "Rp " + currencyFormat.format(transaksi.getTotalHarga()),
                transaksi.getMetodePembayaran()
            };
            tableModel.addRow(row);
        }
        
        System.out.println("✅ Found " + transaksiList.size() + " results");
    }
    
    // ==================== GET TRANSAKSI FROM FORM ====================
    
    private TransaksiPenjualanProduk getTransaksiFromForm() throws Exception {
        // ✅ VALIDASI PRODUK
        if (nama_produk.getSelectedIndex() == 0) {
            throw new Exception("⚠️ Pilih produk!");
        }

        // ✅ VALIDASI PELANGGAN (FIX: Handle both ComboBox selection & manual input)
        Object pelangganObj = nama_pelanggan.getSelectedItem();
        if (pelangganObj == null) {
            throw new Exception("⚠️ Pilih atau isi nama pelanggan!");
        }

        String namaPelangganStr = pelangganObj.toString().trim();
        if (namaPelangganStr.isEmpty() || namaPelangganStr.startsWith("--")) {
            throw new Exception("⚠️ Pilih atau isi nama pelanggan!");
        }

        // ✅ VALIDASI TANGGAL
        if (tanggal.getDate() == null) {
            throw new Exception("⚠️ Pilih tanggal!");
        }

        // ✅ VALIDASI JUMLAH
        String jumlahStr = jumlah_beli.getText().trim();
        if (jumlahStr.isEmpty()) {
            throw new Exception("⚠️ Isi jumlah jual!");
        }

        int jumlahJual;
        try {
            jumlahJual = Integer.parseInt(jumlahStr);
        } catch (NumberFormatException e) {
            throw new Exception("⚠️ Jumlah harus berupa angka!");
        }

        if (jumlahJual <= 0) {
            throw new Exception("⚠️ Jumlah harus > 0!");
        }

        // ✅ VALIDASI TELEPON
        if (telepon.getText().trim().isEmpty()) {
            throw new Exception("⚠️ Isi nomor telepon!");
        }

        // ✅ VALIDASI HARGA SATUAN
        String hargaStr = harga_satuan.getText().trim();
        if (hargaStr.isEmpty()) {
            throw new Exception("⚠️ Harga satuan kosong!");
        }

        double hargaSatuan;
        try {
            hargaSatuan = Double.parseDouble(hargaStr);
        } catch (NumberFormatException e) {
            throw new Exception("⚠️ Harga satuan tidak valid!");
        }

        // ✅ CREATE OBJECT
        TransaksiPenjualanProduk transaksi = new TransaksiPenjualanProduk();

        // Kode Transaksi (auto-generated)
        transaksi.setKodeTransaksi(transaksiPenjualanProdukDAO.generateKodeTransaksi());

        // Tanggal (convert java.util.Date to java.sql.Date)
        java.util.Date utilDate = tanggal.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        transaksi.setTanggalTransaksi(sqlDate);

        // Produk
        String namaProduk = (String) nama_produk.getSelectedItem();
        String kodeProduk = id_produk.getText().trim();
        transaksi.setKodeProduk(kodeProduk);
        transaksi.setNamaProduk(namaProduk);

        // Jumlah & Harga
        transaksi.setJumlahJual(jumlahJual);
        transaksi.setHargaSatuan(hargaSatuan);

        // Pelanggan
        transaksi.setNamaPelanggan(namaPelangganStr);
        transaksi.setTeleponPelanggan(telepon.getText().trim());

        // Pembayaran & Keterangan
        transaksi.setMetodePembayaran((String) metode_pembayaran.getSelectedItem());
        transaksi.setKeterangan(keterangan.getText().trim());

        // Stok
        transaksi.setStokSebelum(Integer.parseInt(stok_sebelum.getText().trim()));
        transaksi.setJumlahJualCopy(Integer.parseInt(jumlah_jual.getText().trim()));
        transaksi.setStokSesudah(Integer.parseInt(stok_sesudah.getText().trim()));

        // ✅ FIX: Total Harga (harus Double atau BigDecimal, bukan Integer)
        double totalHarga = jumlahJual * hargaSatuan;
        transaksi.setTotalHarga(totalHarga);

        return transaksi;
    }
    
    // ==================== CLEAR FORM ====================
    
    private void clearForm() {
        nama_produk.setSelectedIndex(0);
        id_produk.setText("");
        nama_pelanggan.setSelectedIndex(0);
        jumlah_beli.setText("");
        harga_satuan.setText("");
        telepon.setText("");
        metode_pembayaran.setSelectedIndex(0);
        keterangan.setText("");
        stok_sebelum.setText("");
        jumlah_jual.setText("");
        stok_sesudah.setText("");
        total_harga.setText("");
        tanggal.setDate(new Date());
        selectedTransaksi = null;
        System.out.println("✅ Form cleared!");
    }
    
    // ==================== FILL FORM FROM SELECTED ====================
    
    private void fillFormFromSelectedTransaksi() {
        if (selectedTransaksi == null) {
            return;
        }
        
        try {
            tanggal.setDate(selectedTransaksi.getTanggalTransaksi());
            nama_produk.setSelectedItem(selectedTransaksi.getNamaProduk());
            id_produk.setText(selectedTransaksi.getKodeProduk());
            
            jumlah_beli.setText(String.valueOf(selectedTransaksi.getJumlahJual()));
            harga_satuan.setText(String.valueOf(selectedTransaksi.getHargaSatuan()));
            
            nama_pelanggan.setSelectedItem(selectedTransaksi.getNamaPelanggan());
            telepon.setText(selectedTransaksi.getTeleponPelanggan());
            
            metode_pembayaran.setSelectedItem(selectedTransaksi.getMetodePembayaran());
            keterangan.setText(selectedTransaksi.getKeterangan());
            
            stok_sebelum.setText(String.valueOf(selectedTransaksi.getStokSebelum()));
            jumlah_jual.setText(String.valueOf(selectedTransaksi.getJumlahJualCopy()));
            stok_sesudah.setText(String.valueOf(selectedTransaksi.getStokSesudah()));
            
            DecimalFormat df = new DecimalFormat("#,###");
            total_harga.setText("Rp " + df.format(selectedTransaksi.getTotalHarga()));
            
            System.out.println("✅ Form filled!");
            
        } catch (Exception e) {
            System.err.println("❌ Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    private void metode_pembayaranjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metode_pembayaranjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metode_pembayaranjComboBox1ActionPerformed

    private void btnViewPelangganjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPelangganjButton5ActionPerformed
    tableModel.setRowCount(0);
        
        // Change column headers
        tableModel.setColumnCount(0);
        tableModel.addColumn("Nama Pelanggan");
        tableModel.addColumn("Telepon");
        tableModel.addColumn("Total Transaksi");
        tableModel.addColumn("Total Pembelian");
        tableModel.addColumn("Produk Favorit");
        tableModel.addColumn("Terakhir Belanja");
        
        // Get customer summary
        List<TransaksiPenjualanProdukDAO.CustomerSummary> customerList = 
            transaksiPenjualanProdukDAO.getCustomerSummary();
        
        DecimalFormat currencyFormat = new DecimalFormat("#,###");
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        for (TransaksiPenjualanProdukDAO.CustomerSummary customer : customerList) {
            Object[] row = {
                customer.getNamaPelanggan(),
                customer.getTeleponPelanggan(),
                customer.getTotalTransaksi() + " x",
                "Rp " + currencyFormat.format(customer.getTotalPembelian()),
                customer.getProdukFavorit(),
                dateFormat.format(customer.getTerakhirBelanja())
            };
            tableModel.addRow(row);
        }
        
        // Adjust column widths
        tabel_penjualan.getColumnModel().getColumn(0).setPreferredWidth(250);
        tabel_penjualan.getColumnModel().getColumn(1).setPreferredWidth(130);
        tabel_penjualan.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabel_penjualan.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabel_penjualan.getColumnModel().getColumn(4).setPreferredWidth(200);
        tabel_penjualan.getColumnModel().getColumn(5).setPreferredWidth(120);
        
        System.out.println("✅ View Pelanggan: Showing " + customerList.size() + " customers");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnViewPelangganjButton5ActionPerformed

    private void txtCarijTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarijTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarijTextField14ActionPerformed

    private void btnCarijButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarijButton4ActionPerformed
    searchTransaksi();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnCarijButton4ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    tabel_penjualan.clearSelection();
        selectedTransaksi = null;
        clearForm();
        System.out.println("✅ Selection cleared!");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    try {
            TransaksiPenjualanProduk transaksi = getTransaksiFromForm();
            boolean success = transaksiPenjualanProdukDAO.tambahTransaksi(transaksi);
            
            if (success) {
                JOptionPane.showMessageDialog(this,
                    "✅ Transaksi berhasil disimpan!\n\n" +
                    "Kode: " + transaksi.getKodeTransaksi() + "\n" +
                    "Produk: " + transaksi.getNamaProduk() + "\n" +
                    "Jumlah: " + transaksi.getJumlahJual() + " pcs\n" +
                    "Total: Rp " + new DecimalFormat("#,###").format(transaksi.getTotalHarga()),
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadDataToTable();
                loadProdukToComboBox(); // Refresh stok
            } else {
                JOptionPane.showMessageDialog(this,
                    "❌ Gagal menyimpan!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "❌ " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void stok_sesudahjTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_sesudahjTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stok_sesudahjTextField12ActionPerformed

    private void stok_sebelumjTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_sebelumjTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stok_sebelumjTextField11ActionPerformed

    private void total_hargajTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_hargajTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_hargajTextField9ActionPerformed

    private void harga_satuanjTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_satuanjTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_satuanjTextField8ActionPerformed

    private void jumlah_belijTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_belijTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_belijTextField7ActionPerformed

    private void teleponjTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponjTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleponjTextField9ActionPerformed

    private void jumlah_jualjTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_jualjTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_jualjTextField12ActionPerformed

    private void btnViewDetailPenjualanjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailPenjualanjButton5ActionPerformed
    initTable();
        loadDataToTable();
        selectedTransaksi = null;
        System.out.println("✅ View Detail Penjualan: Back to normal view");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailPenjualanjButton5ActionPerformed

    private void id_produkjTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_produkjTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_produkjTextField7ActionPerformed

    private void id_pelangganjTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pelangganjTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pelangganjTextField7ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    // ✅ CEK APAKAH ADA TRANSAKSI YANG DIPILIH
    if (selectedTransaksi == null) {
        JOptionPane.showMessageDialog(this,
            "⚠️ Pilih transaksi dari tabel terlebih dahulu!",
            "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // ✅ KONFIRMASI EDIT
    int confirm = JOptionPane.showConfirmDialog(this,
        "⚠️ Edit transaksi ini?\n\n" +
        "Kode Transaksi: " + selectedTransaksi.getKodeTransaksi() + "\n\n" +
        "Data akan dimuat ke form untuk diedit.\n" +
        "Setelah selesai edit, klik TAMBAH untuk menyimpan perubahan.",
        "Konfirmasi Edit", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.INFORMATION_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // ✅ FILL FORM FROM SELECTED TRANSAKSI
            fillFormFromSelectedTransaksi();
            
            JOptionPane.showMessageDialog(this,
                "✅ Data transaksi dimuat di form!\n\n" +
                "1. Ubah data yang diperlukan\n" +
                "2. Klik tombol TAMBAH untuk menyimpan perubahan\n\n" +
                "⚠️ Catatan: Edit akan membuat transaksi baru dan menghapus yang lama.",
                "Edit Mode", 
                JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println("✅ Edit mode: Form filled with transaction data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "❌ Error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    } else {
        selectedTransaksi = null;
        System.out.println("✅ Edit cancelled by user");
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
     searchTransaksi();
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void tabel_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penjualanMouseClicked
     int selectedRow = tabel_penjualan.getSelectedRow();
        
        if (selectedRow >= 0) {
            String kodeTransaksi = tabel_penjualan.getValueAt(selectedRow, 0).toString();
            selectedTransaksi = transaksiPenjualanProdukDAO.getTransaksiByKode(kodeTransaksi);
            
            if (selectedTransaksi != null) {
                fillFormFromSelectedTransaksi();
                System.out.println("✅ Selected & auto-filled: " + kodeTransaksi);
            }
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_tabel_penjualanMouseClicked

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
    // ✅ CEK APAKAH ADA TRANSAKSI YANG DIPILIH
    if (selectedTransaksi == null) {
        JOptionPane.showMessageDialog(this,
            "⚠️ Pilih transaksi dari tabel terlebih dahulu!",
            "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // ✅ KONFIRMASI HAPUS
    int confirm = JOptionPane.showConfirmDialog(this,
        "⚠️ Yakin ingin menghapus transaksi ini?\n\n" +
        "Kode Transaksi: " + selectedTransaksi.getKodeTransaksi() + "\n" +
        "Produk: " + selectedTransaksi.getNamaProduk() + "\n" +
        "Pelanggan: " + selectedTransaksi.getNamaPelanggan() + "\n" +
        "Total: Rp " + new DecimalFormat("#,###").format(selectedTransaksi.getTotalHarga()) + "\n\n" +
        "⚠️ Stok produk akan dikembalikan!",
        "Konfirmasi Hapus", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // ✅ HAPUS TRANSAKSI (DAO akan handle pengembalian stok)
            boolean success = transaksiPenjualanProdukDAO.hapusTransaksi(selectedTransaksi.getKodeTransaksi());
            
            if (success) {
                JOptionPane.showMessageDialog(this,
                    "✅ Transaksi berhasil dihapus!\n\n" +
                    "Stok produk telah dikembalikan.",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
                // Clear form & refresh
                clearForm();
                loadDataToTable();
                loadProdukToComboBox(); // Refresh produk (stok berubah)
                selectedTransaksi = null;
                
                System.out.println("✅ Transaksi deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this,
                    "❌ Gagal menghapus transaksi!\n\nSilakan coba lagi.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "❌ Error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    } else {
        System.out.println("✅ Delete cancelled by user");
    } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnHAPUSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnViewDetailPenjualan;
    private javax.swing.JButton btnViewPelanggan;
    private javax.swing.JTextField harga_satuan;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JTextField id_produk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jumlah_beli;
    private javax.swing.JTextField jumlah_jual;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JComboBox<String> metode_pembayaran;
    private javax.swing.JComboBox<String> nama_pelanggan;
    private javax.swing.JComboBox<String> nama_produk;
    private javax.swing.JTextField stok_sebelum;
    private javax.swing.JTextField stok_sesudah;
    private javax.swing.JTable tabel_penjualan;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField telepon;
    private javax.swing.JTextField total_harga;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
