/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.okesalon.view.laporan.LaporanArsip;
import com.okesalon.view.laporan.LaporanCustomer;
import com.okesalon.view.laporan.LaporanKeuangan;
import com.okesalon.view.laporan.LaporanOperasional;
import com.okesalon.view.laporan.LaporanStok;
import com.okesalon.view.master.FormArsipDokumen;
import com.okesalon.view.master.FormKaryawan;
import com.okesalon.view.master.FormLayanan;
import com.okesalon.view.master.FormPelanggan;
import com.okesalon.view.master.FormProduk;
import com.okesalon.view.sistem.FormDashboard;
import com.okesalon.view.transaksi.FormAbsensi;
import com.okesalon.view.transaksi.FormTransaksiLayanan;
import com.okesalon.view.transaksi.FormTransaksiPembelianProduk;
import com.okesalon.view.transaksi.FormTransaksiPenjualanProduk;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author T480
 */
public class MainApp extends javax.swing.JFrame {

    private final Color COLOR_DEFAULT = new Color(255, 255, 255);
    private final Color COLOR_HOVER = new Color(255, 220, 230);
    private final Color COLOR_ACTIVE = new Color(255, 192, 203);
    private final Color COLOR_PANEL_BG = new Color(240, 240, 240);
    private final Color COLOR_INDICATOR_DEFAULT = new Color(255, 255, 255);
    private final Color COLOR_INDICATOR_HOVER = new Color(255, 204, 255);
    private final Color COLOR_TEXT_DEFAULT = new Color(150, 150, 150);
    private final Color COLOR_TEXT_ACTIVE = new Color(0, 0, 0);        
    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        setupHoverEffects();
          // Load dashboard di awal
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        pnl_dashboard = new javax.swing.JPanel();
        ind_dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_masterdata = new javax.swing.JLabel();
        pnl_layanan = new javax.swing.JPanel();
        ind_layanan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnl_karyawan = new javax.swing.JPanel();
        ind_karyawan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnl_pelanggan = new javax.swing.JPanel();
        ind_pelanggan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnl_produk = new javax.swing.JPanel();
        ind_produk = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnl_arsipdokumen = new javax.swing.JPanel();
        ind_arsipdokumen = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_transaksi = new javax.swing.JLabel();
        pnl_transaksilayanan = new javax.swing.JPanel();
        ind_transaksilayanan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnl_absensi = new javax.swing.JPanel();
        ind_absensi = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnl_produkbeli = new javax.swing.JPanel();
        ind_produkbeli = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnl_produkjual = new javax.swing.JPanel();
        ind_produkjual = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_laporan = new javax.swing.JLabel();
        pnl_laporankeuangan = new javax.swing.JPanel();
        ind_laporankeuangan = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pnl_laporanoperasional = new javax.swing.JPanel();
        ind_laporanoperasional = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pnl_laporanstok = new javax.swing.JPanel();
        ind_laporanstok = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pnl_laporancustomer = new javax.swing.JPanel();
        ind_laporancustomer = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pnl_laporanarsip = new javax.swing.JPanel();
        ind_laporanarsip = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        pnl_kanan = new javax.swing.JPanel();
        navbar = new keeptoo.KGradientPanel();
        pnl_dasar = new javax.swing.JPanel();
        panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(427, 1356));
        sidebar.setRequestFocusEnabled(false);
        sidebar.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoSalon.png"))); // NOI18N
        jLabel2.setText("Oke Salon");
        jLabel2.setIconTextGap(10);
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 80));
        sidebar.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        ind_dashboard.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout ind_dashboardLayout = new javax.swing.GroupLayout(ind_dashboard);
        ind_dashboard.setLayout(ind_dashboardLayout);
        ind_dashboardLayout.setHorizontalGroup(
            ind_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_dashboardLayout.setVerticalGroup(
            ind_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout pnl_dashboardLayout = new javax.swing.GroupLayout(pnl_dashboard);
        pnl_dashboard.setLayout(pnl_dashboardLayout);
        pnl_dashboardLayout.setHorizontalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_dashboardLayout.createSequentialGroup()
                    .addComponent(ind_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_dashboardLayout.setVerticalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_masterdata.setForeground(new java.awt.Color(153, 153, 153));
        txt_masterdata.setText("MASTER DATA");

        pnl_layanan.setBackground(new java.awt.Color(255, 255, 255));

        ind_layanan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_layananLayout = new javax.swing.GroupLayout(ind_layanan);
        ind_layanan.setLayout(ind_layananLayout);
        ind_layananLayout.setHorizontalGroup(
            ind_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_layananLayout.setVerticalGroup(
            ind_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Layanan");

        javax.swing.GroupLayout pnl_layananLayout = new javax.swing.GroupLayout(pnl_layanan);
        pnl_layanan.setLayout(pnl_layananLayout);
        pnl_layananLayout.setHorizontalGroup(
            pnl_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_layananLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_layananLayout.createSequentialGroup()
                    .addComponent(ind_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_layananLayout.setVerticalGroup(
            pnl_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_layananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_layanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_karyawan.setBackground(new java.awt.Color(255, 255, 255));

        ind_karyawan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_karyawanLayout = new javax.swing.GroupLayout(ind_karyawan);
        ind_karyawan.setLayout(ind_karyawanLayout);
        ind_karyawanLayout.setHorizontalGroup(
            ind_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_karyawanLayout.setVerticalGroup(
            ind_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Karyawan");

        javax.swing.GroupLayout pnl_karyawanLayout = new javax.swing.GroupLayout(pnl_karyawan);
        pnl_karyawan.setLayout(pnl_karyawanLayout);
        pnl_karyawanLayout.setHorizontalGroup(
            pnl_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_karyawanLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_karyawanLayout.createSequentialGroup()
                    .addComponent(ind_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_karyawanLayout.setVerticalGroup(
            pnl_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_karyawanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_pelanggan.setBackground(new java.awt.Color(255, 255, 255));

        ind_pelanggan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_pelangganLayout = new javax.swing.GroupLayout(ind_pelanggan);
        ind_pelanggan.setLayout(ind_pelangganLayout);
        ind_pelangganLayout.setHorizontalGroup(
            ind_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_pelangganLayout.setVerticalGroup(
            ind_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Pelanggan");

        javax.swing.GroupLayout pnl_pelangganLayout = new javax.swing.GroupLayout(pnl_pelanggan);
        pnl_pelanggan.setLayout(pnl_pelangganLayout);
        pnl_pelangganLayout.setHorizontalGroup(
            pnl_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pelangganLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_pelangganLayout.createSequentialGroup()
                    .addComponent(ind_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_pelangganLayout.setVerticalGroup(
            pnl_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_produk.setBackground(new java.awt.Color(255, 255, 255));

        ind_produk.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_produkLayout = new javax.swing.GroupLayout(ind_produk);
        ind_produk.setLayout(ind_produkLayout);
        ind_produkLayout.setHorizontalGroup(
            ind_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_produkLayout.setVerticalGroup(
            ind_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Produk");

        javax.swing.GroupLayout pnl_produkLayout = new javax.swing.GroupLayout(pnl_produk);
        pnl_produk.setLayout(pnl_produkLayout);
        pnl_produkLayout.setHorizontalGroup(
            pnl_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_produkLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_produkLayout.createSequentialGroup()
                    .addComponent(ind_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_produkLayout.setVerticalGroup(
            pnl_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_produkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_produk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_arsipdokumen.setBackground(new java.awt.Color(255, 255, 255));

        ind_arsipdokumen.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_arsipdokumenLayout = new javax.swing.GroupLayout(ind_arsipdokumen);
        ind_arsipdokumen.setLayout(ind_arsipdokumenLayout);
        ind_arsipdokumenLayout.setHorizontalGroup(
            ind_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_arsipdokumenLayout.setVerticalGroup(
            ind_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Arsip Dokumen");

        javax.swing.GroupLayout pnl_arsipdokumenLayout = new javax.swing.GroupLayout(pnl_arsipdokumen);
        pnl_arsipdokumen.setLayout(pnl_arsipdokumenLayout);
        pnl_arsipdokumenLayout.setHorizontalGroup(
            pnl_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_arsipdokumenLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_arsipdokumenLayout.createSequentialGroup()
                    .addComponent(ind_arsipdokumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_arsipdokumenLayout.setVerticalGroup(
            pnl_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_arsipdokumenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_arsipdokumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_arsipdokumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_transaksi.setForeground(new java.awt.Color(153, 153, 153));
        txt_transaksi.setText("TRANSAKSI");

        pnl_transaksilayanan.setBackground(new java.awt.Color(255, 255, 255));

        ind_transaksilayanan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_transaksilayananLayout = new javax.swing.GroupLayout(ind_transaksilayanan);
        ind_transaksilayanan.setLayout(ind_transaksilayananLayout);
        ind_transaksilayananLayout.setHorizontalGroup(
            ind_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_transaksilayananLayout.setVerticalGroup(
            ind_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Transaksi Layanan");

        javax.swing.GroupLayout pnl_transaksilayananLayout = new javax.swing.GroupLayout(pnl_transaksilayanan);
        pnl_transaksilayanan.setLayout(pnl_transaksilayananLayout);
        pnl_transaksilayananLayout.setHorizontalGroup(
            pnl_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_transaksilayananLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_transaksilayananLayout.createSequentialGroup()
                    .addComponent(ind_transaksilayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_transaksilayananLayout.setVerticalGroup(
            pnl_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_transaksilayananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_transaksilayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_transaksilayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_absensi.setBackground(new java.awt.Color(255, 255, 255));

        ind_absensi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_absensiLayout = new javax.swing.GroupLayout(ind_absensi);
        ind_absensi.setLayout(ind_absensiLayout);
        ind_absensiLayout.setHorizontalGroup(
            ind_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_absensiLayout.setVerticalGroup(
            ind_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Absensi");

        javax.swing.GroupLayout pnl_absensiLayout = new javax.swing.GroupLayout(pnl_absensi);
        pnl_absensi.setLayout(pnl_absensiLayout);
        pnl_absensiLayout.setHorizontalGroup(
            pnl_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_absensiLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_absensiLayout.createSequentialGroup()
                    .addComponent(ind_absensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_absensiLayout.setVerticalGroup(
            pnl_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_absensiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_absensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_produkbeli.setBackground(new java.awt.Color(255, 255, 255));

        ind_produkbeli.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_produkbeliLayout = new javax.swing.GroupLayout(ind_produkbeli);
        ind_produkbeli.setLayout(ind_produkbeliLayout);
        ind_produkbeliLayout.setHorizontalGroup(
            ind_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_produkbeliLayout.setVerticalGroup(
            ind_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Pembelian Produk");

        javax.swing.GroupLayout pnl_produkbeliLayout = new javax.swing.GroupLayout(pnl_produkbeli);
        pnl_produkbeli.setLayout(pnl_produkbeliLayout);
        pnl_produkbeliLayout.setHorizontalGroup(
            pnl_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_produkbeliLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_produkbeliLayout.createSequentialGroup()
                    .addComponent(ind_produkbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_produkbeliLayout.setVerticalGroup(
            pnl_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_produkbeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_produkbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_produkbeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_produkjual.setBackground(new java.awt.Color(255, 255, 255));

        ind_produkjual.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_produkjualLayout = new javax.swing.GroupLayout(ind_produkjual);
        ind_produkjual.setLayout(ind_produkjualLayout);
        ind_produkjualLayout.setHorizontalGroup(
            ind_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_produkjualLayout.setVerticalGroup(
            ind_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Penjualan Produk");

        javax.swing.GroupLayout pnl_produkjualLayout = new javax.swing.GroupLayout(pnl_produkjual);
        pnl_produkjual.setLayout(pnl_produkjualLayout);
        pnl_produkjualLayout.setHorizontalGroup(
            pnl_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_produkjualLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_produkjualLayout.createSequentialGroup()
                    .addComponent(ind_produkjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_produkjualLayout.setVerticalGroup(
            pnl_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_produkjualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_produkjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_produkjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_laporan.setForeground(new java.awt.Color(153, 153, 153));
        txt_laporan.setText("LAPORAN");

        pnl_laporankeuangan.setBackground(new java.awt.Color(255, 255, 255));

        ind_laporankeuangan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_laporankeuanganLayout = new javax.swing.GroupLayout(ind_laporankeuangan);
        ind_laporankeuangan.setLayout(ind_laporankeuanganLayout);
        ind_laporankeuanganLayout.setHorizontalGroup(
            ind_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_laporankeuanganLayout.setVerticalGroup(
            ind_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Laporan Keuangan");

        javax.swing.GroupLayout pnl_laporankeuanganLayout = new javax.swing.GroupLayout(pnl_laporankeuangan);
        pnl_laporankeuangan.setLayout(pnl_laporankeuanganLayout);
        pnl_laporankeuanganLayout.setHorizontalGroup(
            pnl_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporankeuanganLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_laporankeuanganLayout.createSequentialGroup()
                    .addComponent(ind_laporankeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_laporankeuanganLayout.setVerticalGroup(
            pnl_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporankeuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_laporankeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_laporankeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_laporanoperasional.setBackground(new java.awt.Color(255, 255, 255));

        ind_laporanoperasional.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_laporanoperasionalLayout = new javax.swing.GroupLayout(ind_laporanoperasional);
        ind_laporanoperasional.setLayout(ind_laporanoperasionalLayout);
        ind_laporanoperasionalLayout.setHorizontalGroup(
            ind_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_laporanoperasionalLayout.setVerticalGroup(
            ind_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("Laporan Operasional");

        javax.swing.GroupLayout pnl_laporanoperasionalLayout = new javax.swing.GroupLayout(pnl_laporanoperasional);
        pnl_laporanoperasional.setLayout(pnl_laporanoperasionalLayout);
        pnl_laporanoperasionalLayout.setHorizontalGroup(
            pnl_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanoperasionalLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_laporanoperasionalLayout.createSequentialGroup()
                    .addComponent(ind_laporanoperasional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_laporanoperasionalLayout.setVerticalGroup(
            pnl_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanoperasionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_laporanoperasionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_laporanoperasional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_laporanstok.setBackground(new java.awt.Color(255, 255, 255));

        ind_laporanstok.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_laporanstokLayout = new javax.swing.GroupLayout(ind_laporanstok);
        ind_laporanstok.setLayout(ind_laporanstokLayout);
        ind_laporanstokLayout.setHorizontalGroup(
            ind_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_laporanstokLayout.setVerticalGroup(
            ind_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("Laporan Stok");

        javax.swing.GroupLayout pnl_laporanstokLayout = new javax.swing.GroupLayout(pnl_laporanstok);
        pnl_laporanstok.setLayout(pnl_laporanstokLayout);
        pnl_laporanstokLayout.setHorizontalGroup(
            pnl_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanstokLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_laporanstokLayout.createSequentialGroup()
                    .addComponent(ind_laporanstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_laporanstokLayout.setVerticalGroup(
            pnl_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanstokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_laporanstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_laporanstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_laporancustomer.setBackground(new java.awt.Color(255, 255, 255));

        ind_laporancustomer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_laporancustomerLayout = new javax.swing.GroupLayout(ind_laporancustomer);
        ind_laporancustomer.setLayout(ind_laporancustomerLayout);
        ind_laporancustomerLayout.setHorizontalGroup(
            ind_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_laporancustomerLayout.setVerticalGroup(
            ind_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 153, 153));
        jLabel32.setText("Laporan Customer");

        javax.swing.GroupLayout pnl_laporancustomerLayout = new javax.swing.GroupLayout(pnl_laporancustomer);
        pnl_laporancustomer.setLayout(pnl_laporancustomerLayout);
        pnl_laporancustomerLayout.setHorizontalGroup(
            pnl_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporancustomerLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_laporancustomerLayout.createSequentialGroup()
                    .addComponent(ind_laporancustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_laporancustomerLayout.setVerticalGroup(
            pnl_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporancustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_laporancustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_laporancustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_laporanarsip.setBackground(new java.awt.Color(255, 255, 255));

        ind_laporanarsip.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_laporanarsipLayout = new javax.swing.GroupLayout(ind_laporanarsip);
        ind_laporanarsip.setLayout(ind_laporanarsipLayout);
        ind_laporanarsipLayout.setHorizontalGroup(
            ind_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        ind_laporanarsipLayout.setVerticalGroup(
            ind_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 153, 153));
        jLabel34.setText("Laporan Arsip");

        javax.swing.GroupLayout pnl_laporanarsipLayout = new javax.swing.GroupLayout(pnl_laporanarsip);
        pnl_laporanarsip.setLayout(pnl_laporanarsipLayout);
        pnl_laporanarsipLayout.setHorizontalGroup(
            pnl_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanarsipLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_laporanarsipLayout.createSequentialGroup()
                    .addComponent(ind_laporanarsip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        pnl_laporanarsipLayout.setVerticalGroup(
            pnl_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanarsipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_laporanarsipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ind_laporanarsip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_layanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_produk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_transaksilayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_absensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_produkbeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_produkjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_masterdata)
                            .addComponent(txt_transaksi)
                            .addComponent(txt_laporan))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnl_laporankeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_laporanoperasional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_laporanstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_laporancustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_laporanarsip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_arsipdokumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnl_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_masterdata)
                .addGap(18, 18, 18)
                .addComponent(pnl_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_arsipdokumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_transaksi)
                .addGap(18, 18, 18)
                .addComponent(pnl_transaksilayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_absensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_produkbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_produkjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_laporan)
                .addGap(18, 18, 18)
                .addComponent(pnl_laporankeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_laporanoperasional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_laporanstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_laporancustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_laporanarsip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1076, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel7);

        sidebar.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        pnl_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pnl_kanan.setLayout(new java.awt.BorderLayout());

        navbar.setkEndColor(new java.awt.Color(255, 153, 255));
        navbar.setkStartColor(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_kanan.add(navbar, java.awt.BorderLayout.PAGE_START);

        pnl_dasar.setBackground(new java.awt.Color(204, 204, 204));

        panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        panel_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnl_dasarLayout = new javax.swing.GroupLayout(pnl_dasar);
        pnl_dasar.setLayout(pnl_dasarLayout);
        pnl_dasarLayout.setHorizontalGroup(
            pnl_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pnl_dasarLayout.setVerticalGroup(
            pnl_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnl_kanan.add(pnl_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setupHoverEffects() {
        // Smooth scrolling
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane1.getVerticalScrollBar().setBlockIncrement(50);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(8, 0));
        
        // Array semua panel menu (SESUAIKAN dengan nama variable Anda!)
        JPanel[] menuPanels = {
            pnl_dashboard,
            pnl_layanan,
            pnl_karyawan,
            pnl_pelanggan,
            pnl_produk,
            pnl_arsipdokumen,
            pnl_transaksilayanan,
            pnl_absensi,
            pnl_produkbeli,
            pnl_produkjual,
            pnl_laporankeuangan,
            pnl_laporanoperasional,
            pnl_laporanstok,
            pnl_laporancustomer,
            pnl_laporanarsip
        };
        
        // Array panel indikator kecil di kiri (SESUAIKAN dengan nama variable Anda!)
        JPanel[] indicatorPanels = {
            ind_dashboard,
            ind_layanan,
            ind_karyawan,
            ind_pelanggan,
            ind_produk,
            ind_arsipdokumen,
            ind_transaksilayanan,
            ind_absensi,
            ind_produkbeli,
            ind_produkjual,
            ind_laporankeuangan,
            ind_laporanoperasional,
            ind_laporanstok,
            ind_laporancustomer,
            ind_laporanarsip
        };
        
        // Setup hover untuk setiap menu
        for (int i = 0; i < menuPanels.length; i++) {
            if (menuPanels[i] != null) {
                JPanel menuPanel = menuPanels[i];
                JPanel indicator = (i < indicatorPanels.length) ? indicatorPanels[i] : null;
                addHoverEffect(menuPanel, indicator);
            }
        }
        
        // Set semua text menu jadi ABU-ABU dulu
        setAllMenuTextColor(COLOR_TEXT_DEFAULT);
        
        // Set Dashboard sebagai active di awal
        if (pnl_dashboard != null) {
            pnl_dashboard.setBackground(COLOR_ACTIVE);
            setMenuTextColor(pnl_dashboard, COLOR_TEXT_ACTIVE); // Text jadi HITAM
            if (ind_dashboard != null) {
                ind_dashboard.setBackground(COLOR_INDICATOR_HOVER);
            }
        }
    }
    
    /**
     * Set warna semua text menu jadi warna tertentu
     */
    private void setAllMenuTextColor(Color color) {
        JPanel[] allMenuPanels = {
            pnl_dashboard, pnl_layanan, pnl_karyawan, pnl_pelanggan, pnl_produk,
            pnl_arsipdokumen, pnl_transaksilayanan, pnl_absensi, pnl_produkbeli,
            pnl_produkjual, pnl_laporankeuangan, pnl_laporanoperasional,
            pnl_laporanstok, pnl_laporancustomer
        };
        
        for (JPanel menuPanel : allMenuPanels) {
            if (menuPanel != null) {
                setMenuTextColor(menuPanel, color);
            }
        }
    }
    
    /**
     * Set warna text untuk satu menu panel
     */
    private void setMenuTextColor(JPanel menuPanel, Color color) {
        for (Component comp : menuPanel.getComponents()) {
            if (comp instanceof JLabel) {
                ((JLabel) comp).setForeground(color);
            }
        }
    }
    
    /**
     * Tambahkan hover effect ke panel menu dan panel indikator kiri
     */
    private void addHoverEffect(final JPanel menuPanel, final JPanel indicatorPanel) {
        menuPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        menuPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (!menuPanel.getBackground().equals(COLOR_ACTIVE)) {
                    // Ubah background menu jadi light pink
                    menuPanel.setBackground(COLOR_HOVER);
                    
                    // Ubah text jadi HITAM saat hover
                    setMenuTextColor(menuPanel, COLOR_TEXT_ACTIVE);
                    
                    // Ubah panel indikator kiri jadi pink muda
                    if (indicatorPanel != null) {
                        indicatorPanel.setBackground(COLOR_INDICATOR_HOVER);
                    }
                }
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                if (!menuPanel.getBackground().equals(COLOR_ACTIVE)) {
                    // Kembali ke default
                    menuPanel.setBackground(COLOR_DEFAULT);
                    
                    // Ubah text kembali jadi ABU-ABU
                    setMenuTextColor(menuPanel, COLOR_TEXT_DEFAULT);
                    
                    // Panel indikator kembali putih
                    if (indicatorPanel != null) {
                        indicatorPanel.setBackground(COLOR_INDICATOR_DEFAULT);
                    }
                }
            }
            
            @Override
            public void mouseClicked(MouseEvent e) {
                // Reset semua menu
                resetAllMenus();
                
                // Set yang diklik jadi active
                menuPanel.setBackground(COLOR_ACTIVE);
                
                // Set text jadi HITAM (active)
                setMenuTextColor(menuPanel, COLOR_TEXT_ACTIVE);
                
                // Set panel indikator jadi pink muda
                if (indicatorPanel != null) {
                    indicatorPanel.setBackground(COLOR_INDICATOR_HOVER);
                }
                
                handleMenuClick(menuPanel);
            }
        });
    }
    
    /**
     * Reset semua menu ke state default
     */
    private void resetAllMenus() {
        // Reset background panel menu
        if (pnl_dashboard != null) pnl_dashboard.setBackground(COLOR_DEFAULT);
        if (pnl_layanan != null) pnl_layanan.setBackground(COLOR_DEFAULT);
        if (pnl_karyawan != null) pnl_karyawan.setBackground(COLOR_DEFAULT);
        if (pnl_pelanggan != null) pnl_pelanggan.setBackground(COLOR_DEFAULT);
        if (pnl_produk != null) pnl_produk.setBackground(COLOR_DEFAULT);
        if (pnl_arsipdokumen != null) pnl_arsipdokumen.setBackground(COLOR_DEFAULT);
        if (pnl_transaksilayanan != null) pnl_transaksilayanan.setBackground(COLOR_DEFAULT);
        if (pnl_absensi != null) pnl_absensi.setBackground(COLOR_DEFAULT);
        if (pnl_produkbeli != null) pnl_produkbeli.setBackground(COLOR_DEFAULT);
        if (pnl_produkjual != null) pnl_produkjual.setBackground(COLOR_DEFAULT);
        if (pnl_laporankeuangan != null) pnl_laporankeuangan.setBackground(COLOR_DEFAULT);
        if (pnl_laporanoperasional != null) pnl_laporanoperasional.setBackground(COLOR_DEFAULT);
        if (pnl_laporanstok != null) pnl_laporanstok.setBackground(COLOR_DEFAULT);
        if (pnl_laporancustomer != null) pnl_laporancustomer.setBackground(COLOR_DEFAULT);
        if (pnl_laporanarsip != null) pnl_laporanarsip.setBackground(COLOR_DEFAULT);
        
        // Reset text color jadi ABU-ABU
        setAllMenuTextColor(COLOR_TEXT_DEFAULT);
        
        // Reset panel indikator kiri jadi putih
        if (ind_dashboard != null) ind_dashboard.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_layanan != null) ind_layanan.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_karyawan != null) ind_karyawan.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_pelanggan != null) ind_pelanggan.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_produk != null) ind_produk.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_arsipdokumen != null) ind_arsipdokumen.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_transaksilayanan != null) ind_transaksilayanan.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_absensi != null) ind_absensi.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_produkbeli != null) ind_produkbeli.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_produkjual != null) ind_produkjual.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_laporankeuangan != null) ind_laporankeuangan.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_laporanoperasional != null) ind_laporanoperasional.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_laporanstok != null) ind_laporanstok.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_laporancustomer != null) ind_laporancustomer.setBackground(COLOR_INDICATOR_DEFAULT);
        if (ind_laporanarsip != null) ind_laporanarsip.setBackground(COLOR_INDICATOR_DEFAULT);
    }
    
    private void handleMenuClick(JPanel menuPanel) {
        panel_utama.removeAll();
        if (menuPanel == pnl_dashboard) {            
            panel_utama.add(new FormDashboard());
            
        } else if (menuPanel == pnl_layanan) {
            panel_utama.add(new FormLayanan());
            
        } else if (menuPanel == pnl_karyawan) {
            panel_utama.add(new FormKaryawan());
            
        } else if (menuPanel == pnl_pelanggan) {           
            panel_utama.add(new FormPelanggan());
            
        } else if (menuPanel == pnl_produk) {          
            panel_utama.add(new FormProduk());
            
        } else if (menuPanel == pnl_arsipdokumen) {          
            panel_utama.add(new FormArsipDokumen());
            
        } else if (menuPanel == pnl_transaksilayanan) {            
            panel_utama.add(new FormTransaksiLayanan());
            
        } else if (menuPanel == pnl_absensi) {            
            panel_utama.add(new FormAbsensi());
            
        } else if (menuPanel == pnl_produkbeli) {           
            panel_utama.add(new FormTransaksiPembelianProduk());
            
        } else if (menuPanel == pnl_produkjual) {           
            panel_utama.add(new FormTransaksiPenjualanProduk());
            
        } else if (menuPanel == pnl_laporankeuangan) {           
            panel_utama.add(new LaporanKeuangan());
            
        } else if (menuPanel == pnl_laporanoperasional) {            
            panel_utama.add(new LaporanOperasional());
            
        } else if (menuPanel == pnl_laporanstok) {            
            panel_utama.add(new LaporanStok());
            
        } else if (menuPanel == pnl_laporancustomer) {            
            panel_utama.add(new LaporanCustomer());
            
        } else if (menuPanel == pnl_laporanarsip) {           
            panel_utama.add(new LaporanArsip());
        }
        
        
        panel_utama.revalidate();
        panel_utama.repaint();
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(MainApp.MAXIMIZED_BOTH);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ind_absensi;
    private javax.swing.JPanel ind_arsipdokumen;
    private javax.swing.JPanel ind_dashboard;
    private javax.swing.JPanel ind_karyawan;
    private javax.swing.JPanel ind_laporanarsip;
    private javax.swing.JPanel ind_laporancustomer;
    private javax.swing.JPanel ind_laporankeuangan;
    private javax.swing.JPanel ind_laporanoperasional;
    private javax.swing.JPanel ind_laporanstok;
    private javax.swing.JPanel ind_layanan;
    private javax.swing.JPanel ind_pelanggan;
    private javax.swing.JPanel ind_produk;
    private javax.swing.JPanel ind_produkbeli;
    private javax.swing.JPanel ind_produkjual;
    private javax.swing.JPanel ind_transaksilayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel navbar;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel pnl_absensi;
    private javax.swing.JPanel pnl_arsipdokumen;
    private javax.swing.JPanel pnl_dasar;
    private javax.swing.JPanel pnl_dashboard;
    private javax.swing.JPanel pnl_kanan;
    private javax.swing.JPanel pnl_karyawan;
    private javax.swing.JPanel pnl_laporanarsip;
    private javax.swing.JPanel pnl_laporancustomer;
    private javax.swing.JPanel pnl_laporankeuangan;
    private javax.swing.JPanel pnl_laporanoperasional;
    private javax.swing.JPanel pnl_laporanstok;
    private javax.swing.JPanel pnl_layanan;
    private javax.swing.JPanel pnl_pelanggan;
    private javax.swing.JPanel pnl_produk;
    private javax.swing.JPanel pnl_produkbeli;
    private javax.swing.JPanel pnl_produkjual;
    private javax.swing.JPanel pnl_transaksilayanan;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel txt_laporan;
    private javax.swing.JLabel txt_masterdata;
    private javax.swing.JLabel txt_transaksi;
    // End of variables declaration//GEN-END:variables
}
