/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okesalon.view.master;
import com.okesalon.dao.KaryawanDAO;
import com.okesalon.model.Karyawan;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.sql.Connection;
import java.text.NumberFormat;
import java.util.*;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author T480
 */
public class FormKaryawan extends javax.swing.JPanel {

    // Variabel instance
    private DefaultTableModel tableModel;
    private KaryawanDAO karyawanDAO;
    private String selectedFotoPath = null;
    private Karyawan selectedKaryawan = null;
    private boolean isViewGajiMode = false;
    private Connection connection;
    
    
    public FormKaryawan() {
        initComponents();
        Connection conn = koneksi.koneksi.getConnection();
    if (conn == null) {
        JOptionPane.showMessageDialog(this, 
            "Koneksi database gagal! Periksa konfigurasi database.",
            "Error Koneksi",
            JOptionPane.ERROR_MESSAGE);
        return;
    } else {
        System.out.println("✅ Koneksi database berhasil!");
    }
        karyawanDAO = new KaryawanDAO();
        initTable();
        setupDynamicSpesialisasi();
        setupStatusRenderer();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_karyawan = new javax.swing.JTable();
        btnViewGaji = new javax.swing.JButton();
        btnViewNormal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        komisi = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        rbResign = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        upload = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        gaji_pokok = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tanggal_bergabung = new com.toedter.calendar.JDateChooser();
        jabatan = new javax.swing.JComboBox<>();
        rbAktif = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        NIK = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        spesialisasi = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        email = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        jLabel3.setText("Master Data Karyawan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(1273, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 153, 255));

        btnTambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCari.setText("Cari");
        btnCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtCari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tabel_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabel_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_karyawanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_karyawan);

        btnViewGaji.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewGaji.setText("View GAJI");
        btnViewGaji.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGajiActionPerformed(evt);
            }
        });

        btnViewNormal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewNormal.setText("View Detail Karyawan");
        btnViewNormal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNormalActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 220, 255));

        jPanel4.setBackground(new java.awt.Color(255, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETAIL DATA KARYAWAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        komisi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        komisi.setPreferredSize(new java.awt.Dimension(6, 32));
        komisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komisijTextField5ActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namajTextField3ActionPerformed(evt);
            }
        });

        rbResign.setBackground(new java.awt.Color(255, 220, 255));
        bgStatus.add(rbResign);
        rbResign.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbResign.setText("Resign");
        rbResign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbResignjRadioButton2ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setText("Alamat Lengkap");

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        alamat.setRows(5);
        jScrollPane3.setViewportView(alamat);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("No Telpon");

        upload.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        upload.setText("Upload");
        upload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Komisi");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Spesialisasi");

        gaji_pokok.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("Tanggal Bergabung");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setText("Status Kepegawaian");

        tanggal_bergabung.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jabatan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stylist", "Beautician", "Nail Artist", "Spa Therapist", "Kasir", "Manager" }));
        jabatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbAktif.setBackground(new java.awt.Color(255, 220, 255));
        bgStatus.add(rbAktif);
        rbAktif.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbAktif.setText("Aktif");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("Email");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Nama Lengkap");

        NIK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIKjTextField1ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setText("Foto Karyawan");

        spesialisasi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        spesialisasi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setText("Gaji Pokok");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setText("Jabatan");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("NIK");

        no_telp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel28))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(no_telp)
                            .addComponent(email)
                            .addComponent(spesialisasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(NIK)))
                    .addComponent(jLabel38)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(jLabel14)
                    .addComponent(jLabel40)
                    .addComponent(jLabel35))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbResign, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggal_bergabung, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upload, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(komisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gaji_pokok, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel35)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(tanggal_bergabung, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(rbAktif)
                            .addComponent(rbResign))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel40))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(upload, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gaji_pokok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(komisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(spesialisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(33, 33, 33)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(598, 598, 598)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnViewGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnViewNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(493, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents
    // Method untuk setup dynamic spesialisasi
private void setupDynamicSpesialisasi() {
        jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSpesialisasi();
            }
        });
        
        // Panggil updateSpesialisasi() saat pertama kali load form
        updateSpesialisasi();
    }
    
    /**
     * Update spesialisasi berdasarkan jabatan yang dipilih
     */
    private void updateSpesialisasi() {
        String Jabatan = jabatan.getSelectedItem().toString();
        
        // Clear semua item dulu
        spesialisasi.removeAllItems();
        
        // Isi spesialisasi sesuai jabatan
        switch (Jabatan) {
            case "Stylist":
                spesialisasi.setEnabled(true);  // ⭐ Aktifkan ComboBox
                spesialisasi.addItem("Hair Cutting");
                spesialisasi.addItem("Hair Coloring");
                spesialisasi.addItem("Hair Treatment");
                spesialisasi.addItem("Hair Styling");
                break;
                
            case "Beautician":
                spesialisasi.setEnabled(true);  // ⭐ Aktifkan ComboBox
                spesialisasi.addItem("Facial Treatment");
                spesialisasi.addItem("Makeup Artist");
                spesialisasi.addItem("Eyelash Extension");
                spesialisasi.addItem("Skincare Specialist");
                break;
                
            case "Nail Artist":
                spesialisasi.setEnabled(true);  // ⭐ Aktifkan ComboBox
                spesialisasi.addItem("Manicure & Pedicure");
                spesialisasi.addItem("Nail Art Design");
                spesialisasi.addItem("Gel Polish");
                spesialisasi.addItem("Nail Extension");
                break;
                
            case "Spa Therapist":
                spesialisasi.setEnabled(true);  // ⭐ Aktifkan ComboBox
                spesialisasi.addItem("Body Massage");
                spesialisasi.addItem("Reflexology");
                spesialisasi.addItem("Hot Stone Therapy");
                spesialisasi.addItem("Aromatherapy");
                break;
                
            // Jabatan non-teknis
            case "Kasir":
            case "Receptionist":
            case "Manager":
            case "Cleaning Service":
                spesialisasi.addItem("Tidak Ada");
                spesialisasi.setEnabled(false); // ⭐ Nonaktifkan ComboBox
                break;
                
            default:
                spesialisasi.setEnabled(true);  // ⭐ Aktifkan untuk default
                spesialisasi.addItem("Umum");
                break;
        }
    }
    
    private void setupStatusRenderer() {
    tabel_karyawan.getColumnModel().getColumn(8).setCellRenderer(
        new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                
                Component cell = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
                
                String status = (String) value;
                
                if (!isSelected) {
                    if ("Aktif".equals(status)) {
                        cell.setBackground(new Color(220, 255, 220));  // Hijau muda
                        cell.setForeground(new Color(0, 128, 0));      // Hijau tua
                    } else if ("Resign".equals(status)) {
                        cell.setBackground(new Color(255, 220, 220));  // Merah muda
                            cell.setForeground(new Color(200, 0, 0));
                    }
                }
                
                setHorizontalAlignment(SwingConstants.CENTER);
                return cell;
            }
        }
    );
}

    
    
    // ==================== INISIALISASI ====================
    
    /**
     * Inisialisasi struktur tabel
     */
    private void initTable() {
        System.out.println("🔧 Inisialisasi tabel...");
    
    // ⭐ URUTAN KOLOM HARUS SESUAI
    String[] kolom = {
        "Kode",           
        "NIK",            
        "Nama Lengkap",   
        "Jabatan",        
        "Spesialisasi",   
        "No Telpon",      
        "Gaji Pokok",    
        "Komisi",         
        "Status"          
    };
    
    tableModel = new DefaultTableModel(kolom, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    tabel_karyawan.setModel(tableModel);
    tabel_karyawan.setRowHeight(25);
    tabel_karyawan.getTableHeader().setReorderingAllowed(false);
    }
    
    
    /**
     * Load data dari database ke tabel
     */
    private void loadDataToTable() {
    System.out.println("🔄 Memuat data ke tabel...");
    
    tableModel.setRowCount(0);
    
    List<Karyawan> dataKaryawan = karyawanDAO.getAll();
    
    System.out.println("📊 Jumlah data karyawan: " + dataKaryawan.size());
    
    if (dataKaryawan.isEmpty()) {
        System.out.println("⚠️ Data karyawan kosong!");
        JOptionPane.showMessageDialog(this,
            "Data karyawan masih kosong! Silakan tambahkan data terlebih dahulu.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Format rupiah
    NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    
    for (Karyawan k : dataKaryawan) {
        Object[] row = {
            k.getKodeKaryawan(),                    // Kolom 0: Kode
            k.getNik(),                             // Kolom 1: NIK
            k.getNamaLengkap(),                     // Kolom 2: Nama Lengkap
            k.getJabatan(),                         // Kolom 3: Jabatan ⭐ PERBAIKAN DI SINI
            k.getSpesialisasi(),                    // Kolom 4: Spesialisasi
            k.getNoTelpon(),                        // Kolom 5: No Telpon
            rupiah.format(k.getGajiPokok()),        // Kolom 6: Gaji Pokok
            rupiah.format(k.getKomisi()),           // Kolom 7: Komisi
            k.getStatusKepegawaian()                // Kolom 8: Status
        };
        tableModel.addRow(row);
    }
    
    System.out.println("✅ Data berhasil dimuat ke tabel!");
}
    
    // ==================== VALIDASI & HELPER ====================
    
    /**
     * Ambil data dari form → objek Karyawan
     */
    private Karyawan getKaryawanFromForm() throws Exception {
        // Validasi NIK
        String nik = NIK.getText().trim();
        if (nik.isEmpty()) {
            throw new Exception("NIK tidak boleh kosong!");
        }
        
        // Cek NIK unique (saat tambah atau edit)
        String excludeKode = selectedKaryawan != null ? selectedKaryawan.getKodeKaryawan() : null;
        if (karyawanDAO.isNIKExists(nik, excludeKode)) {
            throw new Exception("NIK sudah terdaftar! Gunakan NIK lain.");
        }
        
        // Validasi nama lengkap
        String namaLengkap = nama.getText().trim();
        if (namaLengkap.isEmpty()) {
            throw new Exception("Nama Lengkap tidak boleh kosong!");
        }
        
        String noTelpon = no_telp.getText().trim();
        if (noTelpon.isEmpty()) {
            throw new Exception("No Telpon tidak boleh kosong!");
        }
        
        Date tanggalBergabung = tanggal_bergabung.getDate();
        if (tanggalBergabung == null) {
            throw new Exception("Tanggal Bergabung tidak boleh kosong!");
        }
        
        String gajiStr = gaji_pokok.getText().trim();
        if (gajiStr.isEmpty()) {
            throw new Exception("Gaji Pokok tidak boleh kosong!");
        }
        
        double gajiPokok;
        try {
            gajiPokok = Double.parseDouble(gajiStr);
            if (gajiPokok < 0) throw new Exception("Gaji Pokok tidak boleh negatif!");
        } catch (NumberFormatException e) {
            throw new Exception("Format Gaji Pokok tidak valid!");
        }
        
        String komisiStr = komisi.getText().trim();
        double komisi = 0;
        if (!komisiStr.isEmpty()) {
            try {
                komisi = Double.parseDouble(komisiStr);
                if (komisi < 0) throw new Exception("Komisi tidak boleh negatif!");
            } catch (NumberFormatException e) {
                throw new Exception("Format Komisi tidak valid!");
            }
        }
        
        Karyawan karyawan = new Karyawan();
        karyawan.setNik(nik);
        karyawan.setNamaLengkap(namaLengkap);
        karyawan.setJabatan(jabatan.getSelectedItem().toString());
        karyawan.setSpesialisasi(spesialisasi.getSelectedItem().toString());
        karyawan.setNoTelpon(noTelpon);
        karyawan.setEmail(email.getText().trim());
        karyawan.setAlamatLengkap(alamat.getText().trim());
        karyawan.setTanggalBergabung(tanggalBergabung);
        karyawan.setStatusKepegawaian(rbAktif.isSelected() ? "Aktif" : "Resign");
        karyawan.setGajiPokok(gajiPokok);
        karyawan.setKomisi(komisi);
        karyawan.setFotoKaryawan(selectedFotoPath);
        
        return karyawan;
    }
    
    /**
     * Reset/clear form
     */
    private void clearForm() {
        NIK.setText("");
        nama.setText("");
        jabatan.setSelectedIndex(0);
        spesialisasi.setSelectedIndex(0);
        no_telp.setText("");
        email.setText("");
        alamat.setText("");
        tanggal_bergabung.setDate(null);
        rbAktif.setSelected(true);
        gaji_pokok.setText("");
        komisi.setText("");
        selectedFotoPath = null;
        selectedKaryawan = null;
        tabel_karyawan.clearSelection();
        NIK.requestFocus();
    }
    
    private void NIKjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIKjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIKjTextField1ActionPerformed

    private void namajTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namajTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namajTextField3ActionPerformed

    private void rbResignjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbResignjRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbResignjRadioButton2ActionPerformed

    private void komisijTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komisijTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komisijTextField5ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    try {
            Karyawan karyawan = getKaryawanFromForm();
            
            // Generate kode otomatis
            String kode = karyawanDAO.generateKodeKaryawan();
            karyawan.setKodeKaryawan(kode);
            
            boolean success = karyawanDAO.insert(karyawan);
            
            if (success) {
                loadDataToTable();
                JOptionPane.showMessageDialog(this,
                    "Karyawan berhasil ditambahkan dengan kode: " + kode,
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan data karyawan!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    if (selectedKaryawan == null) {
            JOptionPane.showMessageDialog(this,
                "Pilih data di tabel yang akan diubah!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            Karyawan updated = getKaryawanFromForm();
            updated.setKodeKaryawan(selectedKaryawan.getKodeKaryawan()); // Kode tidak berubah
            
            boolean success = karyawanDAO.update(updated);
            
            if (success) {
                loadDataToTable();
                JOptionPane.showMessageDialog(this,
                    "Data karyawan berhasil diubah!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal mengubah data karyawan!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     if (selectedKaryawan == null) {
            JOptionPane.showMessageDialog(this,
                "Pilih data di tabel yang akan dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus karyawan:\n" +
            selectedKaryawan.getNamaLengkap() + " (" + selectedKaryawan.getKodeKaryawan() + ")?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean success = karyawanDAO.delete(selectedKaryawan.getKodeKaryawan());
            
            if (success) {
                loadDataToTable();
                JOptionPane.showMessageDialog(this,
                    "Data karyawan berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus data karyawan!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    String keyword = txtCari.getText().trim();
    
    if (keyword.isEmpty()) {
        // Jika keyword kosong, refresh sesuai mode
        if (isViewGajiMode) {
            btnViewGajiActionPerformed(null); // Refresh view gaji
        } else {
            loadDataToTable(); // Refresh normal
        }
        return;
    }
    
    tableModel.setRowCount(0);
    
    List<Karyawan> results = karyawanDAO.search(keyword);
    
    NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    
    // ⭐ Cek mode tabel saat ini
    if (isViewGajiMode) {
        // Mode VIEW GAJI - tampilkan 4 kolom
        for (Karyawan k : results) {
            if ("Aktif".equalsIgnoreCase(k.getStatusKepegawaian())) {
                Object[] row = {
                    k.getNamaLengkap(),
                    k.getJabatan(),
                    k.getSpesialisasi(),
                    rupiah.format(k.getGajiPokok())
                };
                tableModel.addRow(row);
            }
        }
        
        // Hitung total dari hasil pencarian
        double totalGaji = 0;
        for (Karyawan k : results) {
            if ("Aktif".equalsIgnoreCase(k.getStatusKepegawaian())) {
                totalGaji += k.getGajiPokok();
            }
        }
        
        // Tambahkan row total
        if (tableModel.getRowCount() > 0) {
            Object[] rowTotal = {
                "TOTAL HASIL PENCARIAN",
                "",
                "",
                rupiah.format(totalGaji)
            };
            tableModel.addRow(rowTotal);
        }
        
    } else {
        // Mode NORMAL - tampilkan 9 kolom
        for (Karyawan k : results) {
            Object[] row = {
                k.getKodeKaryawan(),
                k.getNik(),
                k.getNamaLengkap(),
                k.getJabatan(),
                k.getSpesialisasi(),
                k.getNoTelpon(),
                rupiah.format(k.getGajiPokok()),
                rupiah.format(k.getKomisi()),
                k.getStatusKepegawaian()
            };
            tableModel.addRow(row);
        }
    }
    
    // Tampilkan info hasil pencarian
    int jumlahHasil = tableModel.getRowCount();
    if (isViewGajiMode && jumlahHasil > 0) {
        jumlahHasil--; // Kurangi 1 karena ada row TOTAL
    }
    
    if (jumlahHasil == 0) {
        JOptionPane.showMessageDialog(this,
            "Tidak ada data yang cocok dengan keyword: " + keyword,
            "Info Pencarian",
            JOptionPane.INFORMATION_MESSAGE);
    } else {
        System.out.println("✅ Ditemukan " + jumlahHasil + " data");
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     clearForm();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void tabel_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_karyawanMouseClicked
        int row = tabel_karyawan.getSelectedRow();
        if (row == -1) return;
        
        // Ambil kode dari kolom 0
        String kode = tabel_karyawan.getValueAt(row, 0).toString();
        selectedKaryawan = karyawanDAO.getByKode(kode);
        
        if (selectedKaryawan != null) {
            NIK.setText(selectedKaryawan.getNik());
            nama.setText(selectedKaryawan.getNamaLengkap());
            jabatan.setSelectedItem(selectedKaryawan.getJabatan());
            spesialisasi.setSelectedItem(selectedKaryawan.getSpesialisasi());
            no_telp.setText(selectedKaryawan.getNoTelpon());
            email.setText(selectedKaryawan.getEmail());
            alamat.setText(selectedKaryawan.getAlamatLengkap());
            tanggal_bergabung.setDate(selectedKaryawan.getTanggalBergabung());
            
            if ("Aktif".equalsIgnoreCase(selectedKaryawan.getStatusKepegawaian())) {
                rbAktif.setSelected(true);
            } else {
                rbResign.setSelected(true);
            }
            
            gaji_pokok.setText(String.valueOf((int) selectedKaryawan.getGajiPokok()));
            komisi.setText(String.valueOf((int) selectedKaryawan.getKomisi()));
            selectedFotoPath = selectedKaryawan.getFotoKaryawan();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_karyawanMouseClicked

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
    JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Gambar (JPG, PNG)", "jpg", "jpeg", "png"));
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            selectedFotoPath = file.getAbsolutePath();
            
            JOptionPane.showMessageDialog(this,
                "Foto berhasil dipilih: " + file.getName(),
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_uploadActionPerformed

    private void btnViewGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGajiActionPerformed
    System.out.println("💰 Menampilkan view gaji karyawan...");
    
    // ⭐ Set flag ke mode view gaji
    isViewGajiMode = true;
    
    // Ubah struktur tabel menjadi view gaji
    String[] kolomGaji = {
        "Nama Lengkap", 
        "Jabatan", 
        "Spesialisasi", 
        "Gaji Pokok"
    };
    
    tableModel = new DefaultTableModel(kolomGaji, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    tabel_karyawan.setModel(tableModel);
    tabel_karyawan.setRowHeight(25);
    
    // Atur lebar kolom untuk view gaji
    tabel_karyawan.getColumnModel().getColumn(0).setPreferredWidth(200); // Nama
    tabel_karyawan.getColumnModel().getColumn(1).setPreferredWidth(150); // Jabatan
    tabel_karyawan.getColumnModel().getColumn(2).setPreferredWidth(150); // Spesialisasi
    tabel_karyawan.getColumnModel().getColumn(3).setPreferredWidth(150); // Gaji Pokok
    
    // Ambil data dari database
    List<Karyawan> dataKaryawan = karyawanDAO.getAll();
    
    // Filter hanya karyawan aktif
    NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    
    for (Karyawan k : dataKaryawan) {
        if ("Aktif".equalsIgnoreCase(k.getStatusKepegawaian())) {
            Object[] row = {
                k.getNamaLengkap(),
                k.getJabatan(),
                k.getSpesialisasi(),
                rupiah.format(k.getGajiPokok())
            };
            tableModel.addRow(row);
        }
    }
    
    // Hitung total gaji
    double totalGaji = 0;
    for (Karyawan k : dataKaryawan) {
        if ("Aktif".equalsIgnoreCase(k.getStatusKepegawaian())) {
            totalGaji += k.getGajiPokok();
        }
    }
    
    // Tambahkan row total di akhir
    Object[] rowTotal = {
        "TOTAL GAJI POKOK KARYAWAN AKTIF",
        "",
        "",
        rupiah.format(totalGaji)
    };
    tableModel.addRow(rowTotal);
    
    JOptionPane.showMessageDialog(this,
        "View Gaji berhasil ditampilkan!\n" +
        "Total Gaji Pokok (Karyawan Aktif): " + rupiah.format(totalGaji),
        "Info View Gaji",
        JOptionPane.INFORMATION_MESSAGE);
    
    txtCari.setText("");
    System.out.println("✅ View gaji berhasil ditampilkan. Total: " + rupiah.format(totalGaji));
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnViewGajiActionPerformed

    private void btnViewNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNormalActionPerformed
    System.out.println("📋 Kembali ke view normal...");
    
    // ⭐ Set flag ke mode normal
    isViewGajiMode = false;
    
    // Kembalikan struktur tabel ke normal
    initTable();
    loadDataToTable();
    
    JOptionPane.showMessageDialog(this,
        "Tabel dikembalikan ke tampilan normal.",
        "Info",
        JOptionPane.INFORMATION_MESSAGE);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnViewNormalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIK;
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup bgStatus;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnViewGaji;
    private javax.swing.JButton btnViewNormal;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gaji_pokok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JTextField komisi;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no_telp;
    private javax.swing.JRadioButton rbAktif;
    private javax.swing.JRadioButton rbResign;
    private javax.swing.JComboBox<String> spesialisasi;
    private javax.swing.JTable tabel_karyawan;
    private com.toedter.calendar.JDateChooser tanggal_bergabung;
    private javax.swing.JTextField txtCari;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
