/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okesalon.view.master;
import com.okesalon.dao.ArsipDokumenDAO;
import com.okesalon.model.ArsipDokumen;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.List;

/**
 *
 * @author T480
 */
public class FormArsipDokumen extends javax.swing.JPanel {
    
    // Variabel instance
    private DefaultTableModel tableModel;
    private ArsipDokumenDAO dokumenDAO;
    private ArsipDokumen selectedDokumen = null;
    private String selectedFilePath = null;
    private boolean isViewExpiredMode = false;
    /**
     * Creates new form FormArsipDokumen
     */
    public FormArsipDokumen() {
        initComponents();
        dokumenDAO = new ArsipDokumenDAO();
        dokumenDAO = new ArsipDokumenDAO();
        initTable();
        setupComboBoxes();
        loadDataToTable();
        
        // Auto update status expired saat form dibuka
        autoUpdateExpiredStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        Judul = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnViewExpired = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_arsip = new javax.swing.JTable();
        tanggal = new com.toedter.calendar.JDateChooser();
        tanggal_expired = new com.toedter.calendar.JDateChooser();
        btnClear = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        file_path = new javax.swing.JTextField();
        btnViewDetailArsip = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        jLabel3.setText("Arsip Dokumen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(1341, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Kategori Dokumen");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Judul Dokumen");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Dokumen");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("File Path");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Deskripsi");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Status");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Tanggal Expired");

        kategori.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surat Izin Usaha", "Kontrak Karyawan", "Faktur", "Sertifikat" }));
        kategori.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Judul.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        status.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Expired", "Archived" }));
        status.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        deskripsi.setColumns(20);
        deskripsi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deskripsi.setRows(5);
        jScrollPane1.setViewportView(deskripsi);

        btnTambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCari.setText("CARI");
        btnCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnViewExpired.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewExpired.setText("View Expired");
        btnViewExpired.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewExpiredActionPerformed(evt);
            }
        });

        txtCari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tabel_arsip.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabel_arsip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_arsip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_arsipMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_arsip);

        tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tanggal_expired.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpload.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpload.setText("Upload File");
        btnUpload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        file_path.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnViewDetailArsip.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewDetailArsip.setText("View Detail Arsip");
        btnViewDetailArsip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDetailArsip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailArsipActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewDetailArsip, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(file_path)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(274, 274, 274)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(73, 73, 73)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(97, 97, 97))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanggal_expired, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(file_path, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel7)
                                .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggal_expired, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDetailArsip, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(573, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents
    
    // ==================== INISIALISASI ====================
    
    /**
     * Setup ComboBox dengan data
     */
    private void setupComboBoxes() {
        // ComboBox Kategori Dokumen
        kategori.removeAllItems();
        kategori.addItem("Surat Izin Usaha");
        kategori.addItem("Kontrak Karyawan");
        kategori.addItem("Kontrak Supplier");
        kategori.addItem("Invoice/Kwitansi");
        kategori.addItem("Laporan Keuangan");
        kategori.addItem("Sertifikat Pelatihan");
        kategori.addItem("Dokumen Pajak");
        kategori.addItem("Asuransi");
        kategori.addItem("Perjanjian Kerjasama");
        kategori.addItem("Dokumen Lainnya");
        
        // ComboBox Status
        kategori.removeAllItems();
        kategori.addItem("Aktif");
        kategori.addItem("Non-Aktif");
        kategori.addItem("Expired");
    }
    
    /**
     * Inisialisasi struktur tabel
     */
    private void initTable() {
        String[] kolom = {
            "ID Dokumen",
            "Judul Dokumen",
            "Kategori",
            "Tanggal Dokumen",
            "Tanggal Expired",
            "Status"
        };
        
        tableModel = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tabel_arsip.setModel(tableModel);
        tabel_arsip.setRowHeight(25);
        tabel_arsip.getTableHeader().setReorderingAllowed(false);
        
        // Atur lebar kolom
        tabel_arsip.getColumnModel().getColumn(0).setPreferredWidth(90);   // ID
        tabel_arsip.getColumnModel().getColumn(1).setPreferredWidth(250);  // Judul
        tabel_arsip.getColumnModel().getColumn(2).setPreferredWidth(150);  // Kategori
        tabel_arsip.getColumnModel().getColumn(3).setPreferredWidth(110);  // Tgl Dokumen
        tabel_arsip.getColumnModel().getColumn(4).setPreferredWidth(110);  // Tgl Expired
        tabel_arsip.getColumnModel().getColumn(5).setPreferredWidth(80);   // Status
    }
    
    /**
     * Load data dari database ke tabel
     */
    private void loadDataToTable() {
        tableModel.setRowCount(0);
        
        List<ArsipDokumen> dataDokumen = dokumenDAO.getAll();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        for (ArsipDokumen d : dataDokumen) {
            String tglExpired = d.getTanggalExpired() != null ? 
                               sdf.format(d.getTanggalExpired()) : "-";
            
            Object[] row = {
                d.getIdDokumen(),
                d.getJudulDokumen(),
                d.getKategoriDokumen(),
                sdf.format(d.getTanggalDokumen()),
                tglExpired,
                d.getStatus()
            };
            tableModel.addRow(row);
        }
    }
    
    /**
     * Auto update status dokumen yang sudah expired
     */
    private void autoUpdateExpiredStatus() {
        int updated = dokumenDAO.autoUpdateStatusExpired();
        if (updated > 0) {
            System.out.println("✅ " + updated + " dokumen diupdate menjadi Expired");
        }
    }
    
    /**
     * Open file dengan aplikasi default
     */
    private void openFile() {
        if (selectedDokumen == null || selectedDokumen.getFilePath() == null) {
            JOptionPane.showMessageDialog(this,
                "Tidak ada file yang terhubung dengan dokumen ini.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        File file = new File(selectedDokumen.getFilePath());
        
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this,
                "File tidak ditemukan!\n" +
                "Path: " + selectedDokumen.getFilePath(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Buka file dengan aplikasi default OS
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(file);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Desktop tidak didukung di sistem ini.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal membuka file: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    // ==================== VALIDASI & HELPER ====================
    
    /**
     * Ambil data dari form → objek ArsipDokumen
     */
    private ArsipDokumen getDokumenFromForm() throws Exception {
        // Validasi judul dokumen
        String judul = Judul.getText().trim();
        if (judul.isEmpty()) {
            throw new Exception("Judul Dokumen tidak boleh kosong!");
        }
        
        // Validasi tanggal dokumen
        Date tanggalDokumen = tanggal.getDate();
        if (tanggalDokumen == null) {
            throw new Exception("Tanggal Dokumen tidak boleh kosong!");
        }
        
        // Buat objek ArsipDokumen
        ArsipDokumen dokumen = new ArsipDokumen();
        dokumen.setKategoriDokumen(kategori.getSelectedItem().toString());
        dokumen.setJudulDokumen(judul);
        dokumen.setTanggalDokumen(tanggalDokumen);
        dokumen.setTanggalExpired(tanggal.getDate());
        dokumen.setStatus(status.getSelectedItem().toString());
        dokumen.setDeskripsi(deskripsi.getText().trim());
        dokumen.setFilePath(selectedFilePath);
        
        return dokumen;
    }
    
    /**
     * Reset/clear form
     */
    private void clearForm() {
        kategori.setSelectedIndex(0);
        Judul.setText("");
        tanggal.setDate(new Date());
        tanggal_expired.setDate(null);
        status.setSelectedIndex(0);
        deskripsi.setText("");
        file_path.setText("");
        selectedFilePath = null;
        selectedDokumen = null;
        tabel_arsip.clearSelection();
        
        Judul.requestFocus();
    }
    
    // ==================== UPLOAD FILE ====================
    
    /**
     * Upload file dokumen
     */
    private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File Dokumen");
        
        // Filter untuk berbagai jenis file
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Dokumen (PDF, Word, Excel, Image)", 
            "pdf", "doc", "docx", "xls", "xlsx", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            try {
                // Buat folder untuk menyimpan dokumen jika belum ada
                File folderDokumen = new File("arsip_dokumen");
                if (!folderDokumen.exists()) {
                    folderDokumen.mkdir();
                }
                
                // Copy file ke folder arsip_dokumen dengan nama unik
                String extension = getFileExtension(selectedFile.getName());
                String newFileName = "doc_" + System.currentTimeMillis() + "." + extension;
                File destFile = new File(folderDokumen, newFileName);
                
                Files.copy(selectedFile.toPath(), destFile.toPath(), 
                          StandardCopyOption.REPLACE_EXISTING);
                
                // Simpan path relatif
                selectedFilePath = "arsip_dokumen/" + newFileName;
                
                // Tampilkan nama file di TextField
                file_path.setText(selectedFile.getName());
                
                JOptionPane.showMessageDialog(this,
                    "File berhasil diupload!\n" +
                    "File: " + selectedFile.getName(),
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                    "Gagal mengupload file: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }
    
    /**
     * Helper: Get file extension
     */
    private String getFileExtension(String fileName) {
        int dotIndex = fileName.lastIndexOf('.');
        if (dotIndex > 0 && dotIndex < fileName.length() - 1) {
            return fileName.substring(dotIndex + 1).toLowerCase();
        }
        return "";
    }
    
    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     try {
            ArsipDokumen dokumen = getDokumenFromForm();
            
            // Generate ID otomatis
            String id = dokumenDAO.generateIdDokumen();
            dokumen.setIdDokumen(id);
            
            // Simpan ke database
            boolean success = dokumenDAO.insert(dokumen);
            
            if (success) {
                loadDataToTable();
                JOptionPane.showMessageDialog(this,
                    "Dokumen berhasil ditambahkan dengan ID: " + id,
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                
                // Alert jika dokumen akan expired dalam 30 hari
                if (dokumen.getTanggalExpired() != null) {
                    long hariTersisa = dokumen.getHariTersisa();
                    if (hariTersisa >= 0 && hariTersisa <= 30) {
                        JOptionPane.showMessageDialog(this,
                            "⚠️ PERHATIAN!\n\n" +
                            "Dokumen ini akan expired dalam " + hariTersisa + " hari!\n" +
                            "Tanggal Expired: " + new SimpleDateFormat("dd/MM/yyyy")
                                .format(dokumen.getTanggalExpired()),
                            "Alert Expired",
                            JOptionPane.WARNING_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan data dokumen!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     String keyword = txtCari.getText().trim();
        
        if (keyword.isEmpty()) {
            if (isViewExpiredMode) {
                btnViewExpiredActionPerformed(null);
            } else {
                loadDataToTable();
            }
            return;
        }
        
        // Pencarian hanya untuk mode normal
        if (isViewExpiredMode) {
            JOptionPane.showMessageDialog(this,
                "Pencarian tidak tersedia di mode View Expired.\n" +
                "Kembali ke mode normal terlebih dahulu.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        tableModel.setRowCount(0);
        List<ArsipDokumen> results = dokumenDAO.search(keyword);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        for (ArsipDokumen d : results) {
            String tglExpired = d.getTanggalExpired() != null ? 
                               sdf.format(d.getTanggalExpired()) : "-";
            
            Object[] row = {
                d.getIdDokumen(),
                d.getJudulDokumen(),
                d.getKategoriDokumen(),
                sdf.format(d.getTanggalDokumen()),
                tglExpired,
                d.getStatus()
            };
            tableModel.addRow(row);
        }
        
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak ada data yang cocok dengan keyword: " + keyword,
                "Info Pencarian",
                JOptionPane.INFORMATION_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnViewExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewExpiredActionPerformed
    isViewExpiredMode = true;
        
        String[] kolomExpired = {
            "ID Dokumen",
            "Judul Dokumen",
            "Kategori",
            "Tanggal Expired",
            "Status",
            "Hari Tersisa"
        };
        
        tableModel = new DefaultTableModel(kolomExpired, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tabel_arsip.setModel(tableModel);
        tabel_arsip.setRowHeight(25);
        
        // Atur lebar kolom
        tabel_arsip.getColumnModel().getColumn(0).setPreferredWidth(90);   // ID
        tabel_arsip.getColumnModel().getColumn(1).setPreferredWidth(250);  // Judul
        tabel_arsip.getColumnModel().getColumn(2).setPreferredWidth(150);  // Kategori
        tabel_arsip.getColumnModel().getColumn(3).setPreferredWidth(110);  // Tgl Expired
        tabel_arsip.getColumnModel().getColumn(4).setPreferredWidth(80);   // Status
        tabel_arsip.getColumnModel().getColumn(5).setPreferredWidth(100);  // Hari Tersisa
        
        // Ambil dokumen yang expired atau akan expired dalam 90 hari
        List<ArsipDokumen> dokumenExpired = dokumenDAO.getDokumenExpired(90);
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        if (dokumenExpired.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "✅ Tidak ada dokumen yang expired atau akan expired!\n" +
                "Semua dokumen masih valid.",
                "Info Expired",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Kembali ke view normal
            isViewExpiredMode = false;
            initTable();
            loadDataToTable();
        } else {
            int countExpired = 0;
            int countAkanExpired = 0;
            
            for (ArsipDokumen d : dokumenExpired) {
                long hariTersisa = d.getHariTersisa();
                String statusExpired;
                
                if (hariTersisa < 0) {
                    statusExpired = "Expired ⚠️";
                    countExpired++;
                } else if (hariTersisa == 0) {
                    statusExpired = "Expired Hari Ini! 🔴";
                    countExpired++;
                } else {
                    statusExpired = hariTersisa + " hari lagi ⏰";
                    countAkanExpired++;
                }
                
                Object[] row = {
                    d.getIdDokumen(),
                    d.getJudulDokumen(),
                    d.getKategoriDokumen(),
                    sdf.format(d.getTanggalExpired()),
                    d.getStatus(),
                    statusExpired
                };
                tableModel.addRow(row);
            }
            
            JOptionPane.showMessageDialog(this,
                "⚠️ ALERT DOKUMEN EXPIRED!\n\n" +
                "Dokumen Sudah Expired: " + countExpired + "\n" +
                "Dokumen Akan Expired (90 hari): " + countAkanExpired + "\n\n" +
                "Total: " + dokumenExpired.size() + " dokumen perlu perhatian",
                "Alert Expired",
                JOptionPane.WARNING_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnViewExpiredActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    clearForm();

// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    if (selectedDokumen == null) {
            JOptionPane.showMessageDialog(this,
                "Pilih data di tabel yang akan dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus dokumen:\n" +
            selectedDokumen.getJudulDokumen() + " (" + selectedDokumen.getIdDokumen() + ")?\n\n" +
            "File dokumen tidak akan dihapus dari folder.",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean success = dokumenDAO.delete(selectedDokumen.getIdDokumen());
            
            if (success) {
                loadDataToTable();
                JOptionPane.showMessageDialog(this,
                    "Data dokumen berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus data dokumen!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabel_arsipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_arsipMouseClicked
     int row = tabel_arsip.getSelectedRow();
        if (row == -1) return;
        
        String id = tabel_arsip.getValueAt(row, 0).toString();
        selectedDokumen = dokumenDAO.getById(id);
        
        if (selectedDokumen != null) {
            kategori.setSelectedItem(selectedDokumen.getKategoriDokumen());
            Judul.setText(selectedDokumen.getJudulDokumen());
            tanggal.setDate(selectedDokumen.getTanggalDokumen());
            tanggal_expired.setDate(selectedDokumen.getTanggalExpired());
            status.setSelectedItem(selectedDokumen.getStatus());
            deskripsi.setText(selectedDokumen.getDeskripsi());
            
            // Tampilkan nama file (ekstrak dari path)
            if (selectedDokumen.getFilePath() != null && !selectedDokumen.getFilePath().isEmpty()) {
                File file = new File(selectedDokumen.getFilePath());
                file_path.setText(file.getName());
                selectedFilePath = selectedDokumen.getFilePath();
            } else {
                file_path.setText("");
                selectedFilePath = null;
            }
            
            // Double click untuk buka file
            if (evt.getClickCount() == 2) {
                openFile();
            }
        }   

// TODO add your handling code here:
    }//GEN-LAST:event_tabel_arsipMouseClicked

    private void btnViewDetailArsipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailArsipActionPerformed
    isViewExpiredMode = false;
        initTable();
        loadDataToTable();
        
        JOptionPane.showMessageDialog(this,
            "Tabel dikembalikan ke tampilan normal.",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailArsipActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    if (selectedDokumen == null) {
            JOptionPane.showMessageDialog(this,
                "Pilih data di tabel yang akan diubah!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            ArsipDokumen updated = getDokumenFromForm();
            updated.setIdDokumen(selectedDokumen.getIdDokumen());
            
            // Jika tidak upload file baru, gunakan file lama
            if (selectedFilePath == null) {
                updated.setFilePath(selectedDokumen.getFilePath());
            }
            
            boolean success = dokumenDAO.update(updated);
            
            if (success) {
                loadDataToTable();
                JOptionPane.showMessageDialog(this,
                    "Data dokumen berhasil diubah!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal mengubah data dokumen!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Judul;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnViewDetailArsip;
    private javax.swing.JButton btnViewExpired;
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JTextField file_path;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tabel_arsip;
    private com.toedter.calendar.JDateChooser tanggal;
    private com.toedter.calendar.JDateChooser tanggal_expired;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
